version: '3'
services:
  mongodb:
    image: "centos/mongodb-32-centos7"
    environment:
      MONGODB_USER: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: twitter_scraper
      MONGODB_ADMIN_PASSWORD: password
